In [17]:
import numpy as np
import transformations
from scipy.spatial.transform import Rotation as R
import modern_robotics

def skew(x):
    return np.array([[0, -x[2], x[1]],
                     [x[2], 0, -x[0]],
                     [-x[1], x[0], 0]])


In [55]:
a = np.array(([1, 2, 3],[2, 3, 6],[5, 3, 9]))
b = np.array(([3, 2, 3],[3, 3, 6],[4, 3, 6]))
# at = np.transpose(a)
Rot_Err_Mat = np.dot(a, np.transpose(a))
u = R.from_matrix(Rot_Err_Mat).as_rotvec()
t = R.from_matrix(Rot_Err_Mat).as_euler('zyx')
v = np.array([1, 2, 3])
print(t)
print(u)



[0. 0. 0.]
[0. 0. 0.]


In [29]:
    I = np.identity(3)
    S_Pcur = skew(v)
    theta = v - 1
    u = v + 1
    j_tu = I - (theta/2) * skew(u) + (1 - (np.sinc(theta) / ((np.sinc(theta / 2)) ** 2))) * np.dot(skew(u), skew(u))


    L_out = np.vstack((np.hstack((-I, S_Pcur)), np.hstack((np.zeros([3,3]), j_tu))))

In [20]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ValueError: no unit eigenvector corresponding to eigenvalue 1